dropout: 0.2
fusion_method: add
future_input_size: 12
group_identifier: gauge_id
hidden_size: 64
input_len: 150
input_size: 13
learning_rate: 0.0001
loss_fn: mse
loss_fn_kwargs: {}
num_mixing_layers: 8
output_len: 10
scheduler: cosine_annealing
scheduler_factor: 0.5
scheduler_kwargs:
  T_max: 150
  eta_min: 1.0e-05
scheduler_patience: 2
static_embedding_size: 20
static_size: 22
training_mode: evaluation
use_rev_in: true
