bias: true
bidirectional: true
bidirectional_fusion: add
dropout: 0.2
future_hidden_size: 64
future_input_size: 12
future_layers: 1
group_identifier: gauge_id
hidden_size: 160
input_len: 150
input_size: 13
learning_rate: 0.0001
loss_fn: mse
loss_fn_kwargs: {}
num_layers: 1
output_len: 10
scheduler: cosine_annealing
scheduler_factor: 0.5
scheduler_kwargs:
  T_max: 150
  eta_min: 1.0e-05
scheduler_patience: 5
static_size: 22
training_mode: evaluation
use_rev_in: true
