add_relative_index: false
attn_dropout: 0.29894987729813965
context_length_ratio: 1.0
dropout: 0.318347963953445
encoder_layers: 3
future_input_size: 12
group_identifier: gauge_id
hidden_continuous_size: 128
hidden_size: 32
input_len: 150
input_size: 13
learning_rate: 0.000992851991629171
loss_fn: mse
loss_fn_kwargs: {}
lstm_layers: 2
num_attention_heads: 4
output_len: 10
quantiles:
- 0.5
scheduler: cosine_annealing
scheduler_factor: 0.5
scheduler_kwargs:
  T_max: 150
  eta_min: 1.0e-05
scheduler_patience: 5
static_size: 22
training_mode: evaluation
use_rev_in: true
